<a href="https://colab.research.google.com/github/Akshay-136/AI_ML/blob/master/class4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy - Num Python

In [ ]:
list1=[1,2,3]

In [ ]:
type(list1)

list

In [2]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [3]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim # dimension of this array is

1

In [ ]:
#arange  ---> prinitng a range of values
np.arange(13,18)

array([13, 14, 15, 16, 17])

In [ ]:
for i in range(13,18):
  print(i)

13
14
15
16
17


In [ ]:
np.arange(13,40,4,dtype=float) # will skip every four digit


array([13., 17., 21., 25., 29., 33., 37.])

In [ ]:
np.zeros(8,dtype=int) , np.ones(8,dtype=int)

(array([0, 0, 0, 0, 0, 0, 0, 0]), array([1, 1, 1, 1, 1, 1, 1, 1]))

In [ ]:
#linspace
np.linspace(0,10,5) #divides into 5 equal parts

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.arange(13,40,4, dtype=float)

array([13., 17., 21., 25., 29., 33., 37.])

In [ ]:
#argmax -->
arr2 = np.array([20,5,66,74,74])
arr2

array([20,  5, 66, 74, 74])

In [ ]:
arr2.argmax() #give index

3

In [ ]:
max(arr2)

74

In [ ]:
arr2.argmin() #position of min value

1

In [ ]:
min(arr2)

5

In [ ]:
#slicing and indexing

In [ ]:
arr2[2]=100
arr2

array([ 20,   5, 100,  74,  74])

In [ ]:
arr2[1:3],arr2[-4:]

(array([  5, 100]), array([  5, 100,  74,  74]))

In [14]:
a = np.array([[1,2,3,4],[45,66,7,8]])
a

array([[ 1,  2,  3,  4],
       [45, 66,  7,  8]])

In [17]:
a[0][3] , a[1][2]


(4, 7)

In [8]:
a.ndim #dimension

2

In [19]:
a = np.array([[[1,2,3,4],[2,5,4,7],[45,66,7,8]]]) # created in 0th index only
a

array([[[ 1,  2,  3,  4],
        [ 2,  5,  4,  7],
        [45, 66,  7,  8]]])

In [11]:
a.ndim # so number of square prackets left of starting element predicts dimensions

3

In [21]:
a[0][2][1:4]

array([66,  7,  8])

In [23]:
a = np.array([[[1,2,3,4],[2,5,4,7]],[[45,66,7,8],[5,9,3,7]]])
a

array([[[ 1,  2,  3,  4],
        [ 2,  5,  4,  7]],

       [[45, 66,  7,  8],
        [ 5,  9,  3,  7]]])

In [24]:
a[1]

array([[45, 66,  7,  8],
       [ 5,  9,  3,  7]])

In [26]:
a[1][1]

array([5, 9, 3, 7])

In [31]:
a=np.arange(12) #posibility(6*2,4*3)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a.reshape(6*2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
"""
4- male , 6- female
name, age, salary
aks   23    ?
bsd    ?   54k
"""

In [38]:
np.random.rand(3)

array([0.06098438, 0.30005171, 0.4941243 ])

In [39]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
a.sum()

66

In [41]:
#sqrt & Log
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [42]:
np.log(a)

<ipython-input-42-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527])

In [43]:
np.log10(a)

<ipython-input-43-c769c8e1eb64>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251,
       1.        , 1.04139269])

In [45]:
a=-32
np.abs(a)

32

In [46]:
# Pandas -- Data manipulation

#pandas - > 1) Series & 2) Dataframe

In [48]:
import pandas as pd

s= pd.Series(np.random.rand(6))
s

0    0.458619
1    0.562162
2    0.253492
3    0.235476
4    0.283707
5    0.422183
dtype: float64

In [49]:
s[4]

0.28370717520551714

In [50]:
s[2:4]

2    0.253492
3    0.235476
dtype: float64

In [51]:
s[0]=123
s

0    123.000000
1      0.562162
2      0.253492
3      0.235476
4      0.283707
5      0.422183
dtype: float64

In [52]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [55]:
s.index=['a','b','c','d','e',4]
s

a    123.000000
b      0.562162
c      0.253492
d      0.235476
e      0.283707
4      0.422183
dtype: float64

In [57]:
s['d']

0.2354758507394763

In [58]:
s['b':'e']

b    0.562162
c    0.253492
d    0.235476
e    0.283707
dtype: float64

In [60]:
s['c':4]

c    0.253492
d    0.235476
e    0.283707
4    0.422183
dtype: float64

In [61]:
s[-3:-1]

d    0.235476
e    0.283707
dtype: float64