<a href="https://colab.research.google.com/github/Akshay-136/AI_ML/blob/master/class4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy - Num Python

In [5]:
list1=[1,2,3]

In [6]:
type(list1)

list

In [9]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [8]:
type(arr)

numpy.ndarray

In [10]:
arr.ndim # dimension of this array is

1

In [12]:
#arange  ---> prinitng a range of values
np.arange(13,18)

array([13, 14, 15, 16, 17])

In [23]:
for i in range(13,18):
  print(i)

13
14
15
16
17


In [17]:
np.arange(13,40,4,dtype=float) # will skip every four digit


array([13., 17., 21., 25., 29., 33., 37.])

In [22]:
np.zeros(8,dtype=int) , np.ones(8,dtype=int)

(array([0, 0, 0, 0, 0, 0, 0, 0]), array([1, 1, 1, 1, 1, 1, 1, 1]))

In [24]:
#linspace
np.linspace(0,10,5) #divides into 5 equal parts

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.arange(13,40,4, dtype=float)

array([13., 17., 21., 25., 29., 33., 37.])

In [37]:
#argmax -->
arr2 = np.array([20,5,66,74,74])
arr2

array([20,  5, 66, 74, 74])

In [38]:
arr2.argmax() #give index

3

In [40]:
max(arr2)

74

In [39]:
arr2.argmin() #position of min value

1

In [41]:
min(arr2)

5

In [ ]:
#slicing and indexing

In [47]:
arr2[2]=100
arr2

array([ 20,   5, 100,  74,  74])

In [48]:
arr2[1:3],arr2[-4:]

(array([  5, 100]), array([  5, 100,  74,  74]))